{% set name = "dask-iclx" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dask_iclx-{{ version }}.tar.gz
  sha256: 9767eb265ceb411b27e8b8a656a1ddb5a44a3cdc524692d675a700a2ec7b5141

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - click >=7.0
    - click-didyoumean
    - cryptography
    - dask-core
    - dask-jobqueue >=0.8.1
    - humanize
    - psutil
    - pyyaml
    - watchdog
    - importlib-metadata >=1.0

test:
  imports:
    - dask_iclx
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/runtingt/dask-iclx
  summary: Adapts dask-lxplus to run jobs on the IC HTCondor cluster
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - runtingt
